---
- name: install libs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3
      - python3-pip
      - python3-docker
      - virtualenv
    state: present
    update_cache: yes

- name: install docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: install jsondiff
  pip:
    name: jsondiff
    state: present
    extra_args: --break-system-packages

- name: install python docker module
  pip:
    name: docker==6.1.3
    state: present
    extra_args: --break-system-packages
